schedule lightning talk on OpenStack Image Manager
SovereignCloudStack/calendar pull request #165
Opened 2023-05-17 20:45 UTC by fkr

as discussed in todays (2023-05-17) Team IaaS call

2023-05-17 21:00 UTC, berendt requested changes

2023-05-17 21:00 UTC, berendt commented on lightning_talks.yml
> +    begin: 2023-05-11 15:45:00         # uses default timezone above
2023-06-11?

2023-05-17 21:03 UTC, fkr commented on lightning_talks.yml
> +    begin: 2023-05-11 15:45:00         # uses default timezone above
doh! fixed :)

2023-05-19 08:39 UTC, FriederikeZelke commented
Hey, are you sure with the date? 2023-06-11 is a Sunday.

2023-05-19 19:17 UTC, fkr commented
> Hey, are you sure with the date? 2023-06-11 is a Sunday.

perfect - everyone will have time then ;)
Of course, the 1st of june was meant.

2023-05-21 17:42 UTC, berendt approved these changes

2023-05-21 18:35 UTC, merged

2023-05-22 07:44 UTC, FriederikeZelke reviewed
:-)