Proposal: SIG Monitoring at 11 instead of 12
SovereignCloudStack/calendar pull request #18
Opened 2022-07-15 08:48 UTC by linwalth

The current time (12:05) for SIG Monitoing is not optimal:

- Putting the Meeting back-to-back with the hacking session creates one big block with no interlude to regenerate focus. This is problematic, especially in connection with the following:
- 12:00 is regular lunch time for many people working at the office or coworking spaces. So by missing lunch by an hour the focus of participants suffers.

Personal touch:
- The lack of "social regeneration time" poses a problem for me personally as a neurodivergent person. I think meeting at 11:05 and then having some time for myself would benefit my ability to participate in the hacking session starting at 13:00 in a focused way.

I am sure other people have additional reasons, be they based in time constraints and/or other personal preferences and necessities.

Thus, I would like to propose changing the time from 12:05 to 11:00 or 11:05.

2022-07-15 08:50 UTC, itrich commented
Thank you for your proposal and the very clear explanation why you suggest to switch the regular date. I'm only partly visiting the SIG Monitoring, but this works perferctly for me! +1

2022-07-15 09:54 UTC, matfechner commented
i' would prefer 11:35 am, in cause of one appointment collision, sorry so -1

2022-07-15 10:10 UTC, horazont commented
11:00 is 409 Conflict for me, as is 11:35. 10:00 or 09:00 are irregularly (1/month) conflicting.

2022-07-15 14:52 UTC, frosty-geek commented
Hey, 

I agree with the points you made and totally agree that 12:00-13:00 (MESZ) is considered "reserved for lunch" time-slot, but that's exactly why it works for me to not constantly battle with other meetings.

IMO there is no "optimal" time-slot when you take into consideration that the community consists of several different companies and (at least for now) ~50% of the people in said SIG's are not full-time dedicated to work on SCS (unless they do work within a tender).

So my vote would be to stick with the current setting, even tho I don't like the slot.

my 2¢,
Ralf

2022-07-22 06:07 UTC, itrich commented
The current vote is to stick with the original appointment. I thus will close this issue next week if no further strong objections pop up.

2022-07-23 06:11 UTC, fkr requested changes
Please drop PR, since the majority wants to stick with 12:05.

2022-07-25 08:49 UTC, itrich commented
Won't reschedule as discussed.

2022-07-25 08:49 UTC, closed without merging