Feat/comm call 2024q4
SovereignCloudStack/calendar pull request #324
Opened 2024-10-28 22:43 UTC by garloff

2024-10-29 05:52 UTC, jschoone requested changes

2024-10-29 05:52 UTC, jschoone commented on communitycall-data.yml
> +    "2024-10-10": "kg"
Already covered by #320, please merge that first

2024-10-29 07:47 UTC, jschoone approved these changes

2024-10-29 07:49 UTC, jschoone requested changes

2024-10-29 07:49 UTC, jschoone commented on communitycall-data.yml
> +    "2024-11-09": "mu"
This is a Saturday

2024-10-29 08:14 UTC, jschoone requested changes

2024-10-29 08:14 UTC, jschoone commented on communitycall-data.yml
> +    "2024-11-09": "mu"
```suggestion
    "2024-11-07": "mu"
```
As discussed in Daily, this should be 2024-11-07

2024-10-29 10:08 UTC, jschoone requested changes

2024-10-30 16:16 UTC, garloff commented
OK, @jschoone, somehow you need to re-approve as the "changes requested" flag will otherwise block merging.
TIA!

2024-10-30 18:26 UTC, jschoone approved these changes

2024-11-03 22:06 UTC, merged